### ISSUE TITLE
XssInput should be capitalized

### ISSUE THREAD

**Issue by mouhsinelonly** [FrozenNode/XssInput#2]
XssInput folder name should be capitalized because linux systems are strict when dealing with files and folders naming .

current 
frozennode\xssinput\src\Frozennode\Xssinput\XssInputServiceProvider

should be
frozennode\xssinput\src\Frozennode\XssInput\XssInputServiceProvider

**Comment by benjaminkohl** [comment]
I second this. I ran into this problem when it worked fine for me locally on a Mac then deployed to an Ubuntu server and the service provider could not be found. I forked the repo so I'll make two commits: one where I change the name of the folder to something else entirely, then one where I change it back with the corrected capitalization.

**Comment by janhartigan** [comment]
PRs are welcome. This project is pretty low-priority for me at the moment, but I will merge good PRs.

**Comment by janhartigan** [comment]
Incidentally, I just saw the PR (#3). Merged now.
