### ISSUE TITLE
Cannot access self:: when no class scope is active

### ISSUE THREAD

**Issue by DiederikvandenB** [FrozenNode/XssInput#5]
See screenshot.
![screen shot 2014-02-07 at 17 42 01](https://f.cloud.github.com/assets/6132723/2111866/d3a5e100-9016-11e3-9650-762fd9ef4bfe.png)

Quick workaround is to do this:

``` php
return Security::entity_decode($match[0], 'UTF-8');
```

And then alter the entity_decode function from private to public.

**Comment by janhartigan** [comment]
If you change it to static it might also work. If you patch that up and issue a PR, I'll merge it in.

**Comment by DiederikvandenB** [comment]
Will look at that tonight :)

**Comment by DiederikvandenB** [comment]
Any update on merging this in :)?

**Comment by janhartigan** [comment]
Merged in now. Thanks again for the PR!
